# configs/model/linear_attn_fla.yaml

name: linear_attn_fla
attn_mode: chunk
hidden_size: 512
expand_k: 1.0
expand_v: 1.0
hidden_ratio: 4
intermediate_size: null
num_hidden_layers: 12
num_heads: 8
num_kv_heads: null
feature_map: identity
tie_feature_map_qk: false
norm_q: false
norm_k: false
norm_feature_map: false
hidden_act: swish
elementwise_affine: true
norm_eps: 1e-6
attn: null
use_cache: true
pad_token_id: null
tie_word_embeddings: false
initializer_range: 0.02
fuse_norm: true
fuse_swiglu: true
fuse_cross_entropy: true
fuse_linear_cross_entropy: false
use_l2warp: false
