name: rwkv_trie
vocab_file: /data/maluzhang-folder/zhangjy/projects/nanoLMengine/utils/tokenizer/rwkv_tokenizer/rwkv_vocab_v20230424.txt
use_fast: true
padding_side: right
max_seq_len: 1024
truncation: true